### ISSUE TITLE
5.  add progress bar 

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#11]
## Value Proposition
As a user, I want to see the progress of my tasks more visually by using a graph so that i can gain a greater sense of achievement and motivation.
## Description
![5  Userstory- progress bar](https://user-images.githubusercontent.com/90145001/197490449-98b933e0-9b60-4eb0-970f-b8ab113659d8.png)
## Acception Criteria
- [x] displays a progress bar
## Tasks
- [x] create a new branch for this feature
- [x] create 2 _div_, one for container, one for the progress line
- [x] set the value of the css width of the progress line to match the value of the variable _completedPercent_(in component _TaskCompleted_ already defined)
- [x] add some JS animation if necessary

**Comment by gacsphere** [comment]
Hi Mengzhen,
this is a nice feature for you users!
I'm not sure about your last task: Isn't it the css, where you will define the transitions for your animations?

**Comment by Mengzhen1992** [comment]
@gacsphere i think yes. i need transition and maybe some js code. for example setInterval() and setTimeout() to make my progress bar more interesting
