### ISSUE TITLE
6. add play button and pomodoro timer

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#15]
## Value Proposition
As a user, I want to access the countdown page for each task so that I can focus better on completing the task.
## Description
![6  Userstory- play button and pomodoro timer (1)](https://user-images.githubusercontent.com/90145001/197804903-7861ff60-3107-4dfd-8988-b554d61182fe.png)
![6  Userstory- play button and pomodoro timer (2)](https://user-images.githubusercontent.com/90145001/197804958-3a3c7a79-092c-4dc5-bcfd-28f33819d537.png)
## Acception Criteria
- [x] displays a play button for each ongoing task
- [x] displays a countdown timer for each ongoing task
## Tasks
- [x] create a new branch for this feature
- [x] add a new play button to each of ongoing tasks
- [x] create a new page component _timer_
- [x] add _onClick_ Event Listener and router for the play button, when the play button is clicked, it will jump to the timer page
- [x] on _timer_ page displays a timer, the name and the duration of the clicked task as props will be shown
- [x] add _useEffect_ and _setInterval_ to let the timer after rendering start counting down

**Comment by Roland-Hufnagel** [comment]
This is a good feature for your app! I only miss one task: What happens when the timer ends?

**Comment by CathrinTruchan** [comment]
Hi Mengzhen, very nice user story :) 
In just wanted to ask the same question as Roland :D 
And a cancel/stop button and / or go-back button would be nice. 
But maybe you planned that for another user story?

**Comment by Mengzhen1992** [comment]
@Roland-Hufnagel it will be written in the next userstory. This userstory displays only static timer.

**Comment by Mengzhen1992** [comment]
@CathrinTruchan Thank you for thinking so much about my user story. stop button and pause button have been planned in next userstory but not in the channel user story postet.
