### ISSUE TITLE
8. add pause and stop buttons

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#18]
## Value Proposition
As a user, I want to pause or stop the timer of the ongoing task so that i can have a break or focus on other tasks.
## Description
![Image](https://user-images.githubusercontent.com/90145001/199955004-074c9afc-3960-4977-a759-7b88f80f5bff.png)
![Image](https://user-images.githubusercontent.com/90145001/199955082-3c317066-2989-43e9-9b6d-e71a5277b6df.png)
## Acception Criteria
- [x] displays pause and stop button on the timer page
- [x] when the pause button is clicked, the timer stops counting down and the pause button changes to a start button
- [x] when the stop button is clicked, back to homepage
## Tasks
- [x] create a new branch for this feature
- [x] add 2 _Image_ components in the _timer_ page
- [x] add a new function _handleTogglePause_ and _onClick_ event listener for the pause button, when the pause button is clicked, the state changes and the timer stops counting down, when the pause button is clicked again, the timer starts counting down
- [x] add _onClick_ event listener, _router_ and _handleStop_ function for the stop button, when the stop button is clicked, return to homepage

**Comment by gacsphere** [comment]
Hello Mengzhen,
your timer is a super feature and I'm looking forward to when it is complete.
Your description of the tasks is very detailed. I love that, too. It shows that you know what's to be done.
Very good!

**Comment by Mengzhen1992** [comment]
@gacsphere Gesa thanks for your nice review and comment! 👍
