### ISSUE TITLE
9. add popup when a task is completed

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#19]
## Value Proposition
As a user, when I finish a task I want to be encouraged and go back to the home page so that I will be more motivated to finish other tasks
## Description
![8  Userstory- task is complete](https://user-images.githubusercontent.com/90145001/198296317-7eba8a5b-8ddc-4f8f-ac77-eda5d7dba2ed.png)
## Acception Criteria
- [x] displays a popup when the timer reaches 0
- [x] displays a button "home" in the popup to link to the home page
## Tasks
- [x] create a new branch for this feature
- [x] add a new state _popup_ and set default value to false
- [x] add a new component _FinishPopup_ and import in page _timer_
- [x] in component _FinishPopup_ add _onclick_ event listener, when _home_ button is clicked, call the function _onFInish_
- [x] in function _onFinish_ use fetch to update the status of task in mongodb and use _router_ to return to homepage
