### ISSUE TITLE
7. connect to MongoDB 

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#20]
## Value Proposition
As a user, I want to store my task items after closing the app so that i don't lose my data that i have recorded.
## Description
use MongoDB 
## Acception Criteria
- [x] displays previous input data after reload or when accessing from a different device
- [x] displays real-time data when data is added or deleted
## Tasks
- [x] create a new branch for this feature
- [x] add the environment variable in a new file called `.env.local`
- [x] install Mongoose by using `npm i mongoose`
- [x] add a connection file called `lib/dbConnect.js`
- [x] create a Mongoose model by adding a file `/models/Task.js`
- [x] create an endpoint at `/api/tasks/index.js`, it covers two methods, `GET` and `POST`
- [x] insert code into the function `getServerSideProps` in `/pages/index.js` to load all tasks from the database
- [x] change functions by using `await fetch(url, options)` to send data to server, when changing task status (finished or not finished) / adding tasks / deleting tasks
- [x] insert code into the function `getServerSideProps` in `/pages/timer/[id].js` to load the name and duration of a task
- [x] delete dummy data and array

**Comment by PhilippWeiss85** [comment]
Hi Mengzhen,
looks good to me. However I think you should call it mongoDB instead of mangoDB :)
