### ISSUE TITLE
10. add authentication

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#27]
## Value Proposition
As a user, I only want me to access my data so that the privacy and confidentiality of my data is guaranteed.
## Description
![10  Userstory - authentication(1)](https://user-images.githubusercontent.com/90145001/200570074-417bd0d5-5c0e-42d2-bd29-85106ef062e2.png)
![10  Userstory - authentication(2)](https://user-images.githubusercontent.com/90145001/200570108-4f8bb1c1-f360-4cbc-b4aa-cc1b179cc674.png)
## Acception Criteria
- [ ] displays only a login button when use is not signed in
- [ ] displays task list when user is logged in
## Tasks
- [ ] create a new branch for this feature
- [ ] install nextAuth by using `npm install next-auth`
- [ ] add API route, create a file called `[...nextauth].js` in `pages/api/auth`
- [ ] configure OAuth App in GitHub, copy the client id and secret in file `.env.local`
- [ ] configure Shared session state by using `useSession` and `<SessionProvider>` in `_app.js`
- [ ] add React Hook `useSession()` in `pages/index.js` and `components/Welcome` to check if someone is signed in, when user is signed in, render interactive components and _sign out_ button
- [ ] use the `unstable_getServerSession()` method in Backend to protect an API Route
- [ ] Mongo-DB: Add a `email` and `ticoUser` properties to each task
- [ ] add some css styles

**Comment by CathrinTruchan** [comment]
Nice! Very detailed and clear :) Nothing to add.
