### ISSUE TITLE
11. add Calendar

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#28]
## Value Proposition
As a user, I want toI know how many tasks I have scheduled for each day so that I can manage my tasks and time better.
## Description
![11  Userstory- add calendar(1)](https://user-images.githubusercontent.com/90145001/201298243-b64b9d4b-2b72-4532-992f-e653721ce3ef.png)
![12  Userstory- add calendar(2)](https://user-images.githubusercontent.com/90145001/201298309-043fb288-5f6b-44cf-970b-1b1554559d72.png)
## Acception Criteria
- [x] displays a calendar button on the homepage
- [x] displays the calendar for a view of the tasks each day
- [x] displays a return button on the calendar page
## Tasks
- [x] create a new branch for this feature
- [x] create a new component page `calendar` and add function `Calendar`
- [x] add _useRouter_ to redirect to homepage and from homepage to calendar page
- [x] add _getSession_ to redirect user to start page when user is not signed in
- [x] add _getServerSideProps_ and _find_ method to get the needed tasks data and pass it to the Calendar component
- [x] add some styles
- [x] write some component test

**Comment by gacsphere** [comment]
Wow, a lot to do for the last days. Have fun, Mengzhen! :rocket:
