### ISSUE TITLE
1. display task list

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#4]
## Value Proposition
As a user, I want to display my daily tasks combined with the duration of my tasks, so that i can have an overview of my daily tasks. 
## Description
![1.Userstory-Task list](https://user-images.githubusercontent.com/90145001/196109360-2f211e1c-84d6-4023-982c-5e5a112fa7c0.png)
## Acception Criteria
- [x] displays a task list containing several tasks with the duration to complete them
- [x] displays a username and a date as an example on the homepage
## Tasks
- [x] create a new branch for this feature
- [x] add Welcome component to display welcome text
- [x] add DateDisplay component to display current date
- [x] add example data/array with task items and duration
- [x] add Task component to render a single task in a task list
- [x] implement map method to render all task items in the array

**Comment by F-Kirchhoff** [comment]
This is already looking quite good, but I have some suggestions for you:
- instead of starting with the add button. you should split it into multiple parts:
  - displaying a list of tasks (without any non working features like a start button or checkmark)
  - adding a form for creating a task
  - hiding the form and add a button which reveals it
 
In your value proposition you describe "how" to solve a problem (with an add button). Here you can change the text such that it only talks about the desire of the user, not how this desire is solved.

You can also add more detail in the acceptance criteria and tasks.

**Comment by Mengzhen1992** [comment]
@F-Kirchhoff Thanks a lot for your review and these useful suggestions! I will add more detail in my first user story.

**Comment by Roland-Hufnagel** [comment]
This looks good to me. Good detailed description and tasks. Fine!

**Comment by Mengzhen1992** [comment]
@Roland-Hufnagel Thanks Roland!

**Comment by F-Kirchhoff** [comment]
Hey Mengzhen, this is looking a lot better! The scope is right, the acceptance criteria are good and the tasks are well defined. If you add some more tasks you are ready to go!
- add Welcome component to display welcome text and date
- add DateDisplay component to display current date
- add Task component to render a single task in a task list

**Comment by Mengzhen1992** [comment]
@F-Kirchhoff Thanks for your informative details! I have added these in my tasks.
