### ISSUE TITLE
2.  task with check button

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#5]
## Value Proposition
As a user, I want to check and uncheck my tasks so that i can see and keep track of the status of my daily tasks.
## Description
![2.Userstory- checked button](https://user-images.githubusercontent.com/90145001/196130115-ef4ff35c-0efd-4973-a9e6-b48c4853701e.png)
## Acception Criteria
- [x] display a check button on the left side of the task item
- [x] every task item can be checked and unchecked
- [x] if a task in the "ongoing tasks" box is checked, it will be displayed in a completed task list 
- [x] the number of the completed tasks will be shown 
- [x] the task achievement percent shall be displayed 
## Tasks
- [x] create new branch for this feature
- [x] insert a check button into the task item
- [x] add a Boolean state to handle task item checked or unchecked 
- [x] add TaskCompleted component to display the checked task items  
- [x] add TaskCompletedDisplay component to display the number of the completed Tasks and total tasks also the percent of the tasks achievement

**Comment by F-Kirchhoff** [comment]
Hey Mengzhen, again a good user story! I have some ideas for you still:
- which parts are new components, which one do you reuse?
- if you generalize some components from the last user story, you can reuse them here. Try to keep your code DRY ;)

**Comment by Mengzhen1992** [comment]
@F-Kirchhoff Thanks for these suggestions!
