### ISSUE TITLE
3.  Form and add button

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#6]
## Value Proposition
As a user, I want to add new task items so that i can manage my time each day well.
## Description
![3. Userstory- Form and add button (1)](https://user-images.githubusercontent.com/90145001/196147180-45c2c560-d940-4617-baa1-9a7616b93376.png)
![3. Userstory- Form and add button (2)](https://user-images.githubusercontent.com/90145001/196147229-8e5d3b07-86b1-44e1-ba66-38ac65daa8d0.png)
## Acception Criteria
- [x] displays a new add button on the current ongoing task list
- [x] displays a form containing several inputs, task title, date, start time and duration
- [x] displays two buttons "cancel" and "create"
## Tasks
- [x] create a new branch for this feature
- [x] add a new add button on the current ongoing task list
- [x] create a form with input fields for a _task title_, _date_, _start time_ and _duration_ in a new `Create` component
- [x] create two `Button Components` "cancel" and "create" in the `Create` component
- [x] create a function _appendTask_(_task title_, _date_, _start time_, _duration_) 
- [x] hand down the appendTask function as a prop to the `Create` component
- [x] in the `Create` component use this function and `Formdata` on form submission to append the newly created task
- [x] redireck back to homepage on submission(click create button) or on cancellation

**Comment by CathrinTruchan** [comment]
Very detailed! Looks good to me :) Just one question: Is the form displayed on the same page or is the user redirect to page with the form? Thats not quite clear to me.

**Comment by philmetscher** [comment]
LGTM :) Maybe u should add Components like "create two `Button Components` (cancel, create) in the `Create component`

**Comment by Mengzhen1992** [comment]
@CathrinTruchan Thanks Cathrin for your review, this form will displayed on another page when the Add button is clicked.

**Comment by Mengzhen1992** [comment]
@philmetscher good suggestion! Thank you Phil!
