### ISSUE TITLE
4.  delete button for task item

### ISSUE THREAD

**Issue by Mengzhen1992** [Mengzhen1992/capstone-project#7]
## Value Proposition
As a user, I want to delete task item from completed task list or my current ongoing task list, so that i can focus only on the ongoing tasks.
## Description
![4. Userstory- delete button](https://user-images.githubusercontent.com/90145001/196154959-872e82cb-39da-4cde-8c6e-1902d3f75984.png)
## Acception Criteria
- [x] displays a trash button
- [x] displays the current number of the completed tasks and the percent of the tasks achievement
## Tasks
- [x] create a new branch for this feature
- [x] add a new delete button to each of completed tasks 
- [x] create a function _deleteTask_, the function should delete the task with the respective id
- [x] when a task is deleted, the current number of the completed Tasks and total tasks also the percent of the tasks achievement in the TaskCompletedDisplay component should be changed

**Comment by F-Kirchhoff** [comment]
LGTM! But isn't the 'display the current number of completed tasks already in another user story?

**Comment by kai-franke** [comment]
Looks great! :)
Just for my understanding:  If the focus should be on ongoing tasks, shouldn't they be better shown above the completed tasks on top of the page?

**Comment by Mengzhen1992** [comment]
@F-Kirchhoff yes, so i have used "the" TaskCompletedDisplay component not a TaskCompletedDisplay component

**Comment by Mengzhen1992** [comment]
@kai-franke thank you Kai, i have thought a lot for the location of the ongoing tasks. because i would like insert a progress bar in the completed tasks box later so i have decided to put the completed tasks on the top of the page :)
